# Generated by Django 3.0.5 on 2020-04-21 14:18

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="project", name="nda_organization_name",),
        migrations.AlterField(
            model_name="project",
            name="frameworks",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="resume.Framework"
            ),
        ),
    ]
