language: python
install:
  - pip install pipenv --upgrade
  - make install static
script:
  - make test
cache: pip
jobs:
  include:
    - stage: test
      python: '3.7'
    - stage: test
      python: '3.8'
