dist: xenial
language: python

services:
  - postgresql

env:
  global:
    - ENV_FOR_DYNACONF=travis
    - DYNACONF_DATABASE_URL="postgresql://alex:alex@localhost:5432/sidorov-dev"

install:
  - pip install pipenv --upgrade
  - make venv static

before_script:
  - make resetdb

script:
  - make test

after_success:
  - codecov

cache: pip

jobs:
  include:
    - stage: test
      python: '3.8'
