# Generated by Django 3.0.5 on 2020-05-01 20:13

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="nr_dislikes",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="nr_likes",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
