# Generated by Django 3.0.6 on 2020-05-24 11:13

import django.db.models.deletion
import storages.backends.s3boto3
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="original",
            field=models.FileField(
                storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="blog.Post",
            ),
        ),
    ]
