# Generated by Django 3.0.5 on 2020-04-12 15:40

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Calendar",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "ical_url",
                    models.URLField(
                        blank=True, null=True, unique=True, verbose_name="iCal URL"
                    ),
                ),
                ("ical", models.TextField(blank=True, null=True, verbose_name="iCal")),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                ("synced", models.BooleanField(default=False)),
            ],
            options={"verbose_name_plural": "Calendars",},
        ),
    ]
