# Generated by Django 3.0.5 on 2020-04-13 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="calendar",
            options={"ordering": ("name",), "verbose_name_plural": "Calendars"},
        ),
    ]
