version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.8.5-browsers
      - image: circleci/postgres:9.6.9-alpine
        environment:
          POSTGRES_DB: ci
          POSTGRES_PASSWORD: ci
          POSTGRES_USER: ci
    environment:
      DYNACONF_DATABASE_URL: "postgres://ci:ci@localhost:5432/ci?sslmode=disable"
      ENV_FOR_DYNACONF: ci
      PIPENV_VENV_IN_PROJECT: 1
    steps:
      - checkout
      - run:
          name: (Waiting for Postgres to be ready)
          command: |
            ./.circleci/wait_for_postgresql.sh || exit 1
      - restore_cache:
          keys:
            - cc-venv-{{ checksum "Pipfile.lock" }}
      - run:
          name: Setting up virtualenv
          command: |
            sudo pip install pipenv
            make venv
      - save_cache:
          key: cc-venv-{{ checksum "Pipfile.lock" }}
          paths:
            - ./.venv/
      - run:
          name: Collecting staticfiles
          command: |
            make static
      - run:
          name: Performing Tests
          command: |
            make test
      - codecov/upload:
          file: .coverage
workflows:
  main:
    jobs:
      - build-and-test
