default:
  ALLOWED_HOSTS: []
  AWS_ACCESS_KEY_ID: ""
  AWS_LOCATION: ""
  AWS_S3_REGION_NAME: ""
  AWS_SECRET_ACCESS_KEY: ""
  CELERY_BEAT_INVITATION: -1
  CELERY_BROKER_URL: ""
  DATABASE_URL: ""
  EMAIL_FROM: ""
  EMAIL_HOST: ""
  EMAIL_HOST_PASSWORD: ""
  EMAIL_HOST_USER: ""
  EMAIL_PORT: 0
  EMAIL_USE_SSL: false
  EMAIL_USE_TLS: false
  MODE_CACHING: false
  MODE_DEBUG: false
  MODE_PROFILING: false
  SECRET_KEY: ""
  SENTRY_DSN: ""
  SITE_ID: -1
  TIME_ZONE: ""


development:
  AWS_LOCATION: "development"
  AWS_S3_REGION_NAME: "us-east-1"
  CELERY_BEAT_INVITATION: 30
  MODE_CACHING: 0
  MODE_DEBUG: 1
  MODE_PROFILING: 0
  SECRET_KEY: "xxx"
  SITE_ID: 1
  TIME_ZONE: "Europe/Minsk"


docker:
  AWS_LOCATION: "docker"
  AWS_S3_REGION_NAME: "us-east-1"
  CELERY_BEAT_INVITATION: 30
  CELERY_BROKER_URL: "redis://sidorov-dev-broker"
  DATABASE_URL: "postgresql://alex:alex@sidorov-dev-db:5432/sidorov-dev"
  MODE_CACHING: 0
  MODE_DEBUG: 0
  MODE_PROFILING: 0
  SECRET_KEY: "xxx"
  SITE_ID: 1
  TIME_ZONE: "Europe/Minsk"


heroku:
  AWS_LOCATION: "heroku"
  AWS_S3_REGION_NAME: "us-east-1"
  ALLOWED_HOSTS:
    - .sidorov-dev.herokuapp.com
    - .sidorov.dev
  CELERY_BEAT_INVITATION: 900
  MODE_CACHING: 1
  MODE_DEBUG: 0
  MODE_PROFILING: 0


test:
  EMAIL_FROM: "test@test.name"
  MODE_CACHING: 1
  MODE_DEBUG: 1
  MODE_PROFILING: 0
  SECRET_KEY: "1"
  SITE_ID: 1
  TIME_ZONE: "UTC"


travis:
  EMAIL_FROM: "test@test.name"
  MODE_CACHING: 1
  MODE_DEBUG: 1
  MODE_PROFILING: 0
  SECRET_KEY: "1"
  SITE_ID: 1
  TIME_ZONE: "UTC"

