default:
  ALLOWED_HOSTS: [ ]
  AWS_ACCESS_KEY_ID: ""
  AWS_S3_LOCATION_BLOG_PHOTOS: ""
  AWS_S3_REGION: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_STORAGE_BUCKET: ""
  CELERY_BEAT_CALSYNC: -1
  CELERY_BEAT_INVITATION: -1
  CELERY_BROKER_URL: ""
  DATABASE_URL: ""
  EMAIL_FROM: ""
  EMAIL_HOST: ""
  EMAIL_HOST_PASSWORD: ""
  EMAIL_HOST_USER: ""
  EMAIL_PORT: -1
  EMAIL_USE_SSL: false
  EMAIL_USE_TLS: false
  MODE_CACHING: false
  MODE_DEBUG: false
  MODE_PROFILING: false
  SECRET_KEY: ""
  SENTRY_DSN: ""
  SITE_ID: -1
  TIME_ZONE: ""


development:
  AWS_S3_LOCATION_BLOG_PHOTOS: "blog-photos-dev"
  AWS_S3_REGION: "us-east-1"
  CELERY_BEAT_CALSYNC: 30
  CELERY_BEAT_INVITATION: 30
  MODE_CACHING: 0
  MODE_DEBUG: 1
  MODE_PROFILING: 0
  SECRET_KEY: "xxx"
  SITE_ID: 1
  TIME_ZONE: "Europe/Minsk"


docker:
  AWS_S3_LOCATION_BLOG_PHOTOS: "blog-photos-docker"
  AWS_S3_REGION_NAME: "us-east-1"
  CELERY_BEAT_CALSYNC: 30
  CELERY_BEAT_INVITATION: 30
  CELERY_BROKER_URL: "redis://sidorov-dev-broker"
  DATABASE_URL: "postgresql://alex:alex@sidorov-dev-db:5432/sidorov-dev"
  MODE_CACHING: 0
  MODE_DEBUG: 0
  MODE_PROFILING: 0
  SECRET_KEY: "xxx"
  SITE_ID: 1
  TIME_ZONE: "Europe/Minsk"


heroku:
  ALLOWED_HOSTS:
    - .sidorov-dev.herokuapp.com
    - .sidorov.dev
  AWS_S3_LOCATION_BLOG_PHOTOS: "blog-photos-heroku"
  AWS_S3_REGION_NAME: "us-east-1"
  CELERY_BEAT_CALSYNC: 1800
  CELERY_BEAT_INVITATION: 1800
  MODE_CACHING: 1
  MODE_DEBUG: 0
  MODE_PROFILING: 0


test:
  AWS_S3_LOCATION_BLOG_PHOTOS: "blog-photos-test"
  EMAIL_FROM: "test@test.name"
  MODE_CACHING: 1
  MODE_DEBUG: 1
  MODE_PROFILING: 0
  SECRET_KEY: "1"
  SITE_ID: 1
  TIME_ZONE: "UTC"


ci:
  AWS_S3_LOCATION_BLOG_PHOTOS: "blog-photos-ci"
  EMAIL_FROM: "test@test.name"
  MODE_CACHING: 1
  MODE_DEBUG: 1
  MODE_PROFILING: 0
  SECRET_KEY: "1"
  SITE_ID: 1
  TIME_ZONE: "UTC"
