default:
  ALLOWED_HOSTS: []
  DATABASE_URL: ""
  EMAIL_FROM: ""
  EMAIL_HOST: ""
  EMAIL_HOST_PASSWORD: ""
  EMAIL_HOST_USER: ""
  EMAIL_PORT: 0
  EMAIL_USE_SSL: 0
  EMAIL_USE_TLS: 0
  LOCAL_TIME_ZONE: "UTC"
  MODE_CACHING: false
  MODE_DEBUG: false
  MODE_PROFILING: false
  SECRET_KEY: ""
  SENTRY_DSN: ""
  SITE_ID: 0
  TIME_ZONE: ""


development:
  MODE_CACHING: false
  MODE_DEBUG: true
  MODE_PROFILING: false
  SECRET_KEY: "1"
  SITE_ID: 1
  TIME_ZONE: "Europe/Minsk"


heroku:
  ALLOWED_HOSTS:
    - .sidorov-dev.herokuapp.com
    - .sidorov.dev
    - 127.0.0.1
    - localhost
  MODE_CACHING: true
  MODE_DEBUG: false
  MODE_PROFILING: false


test:
  EMAIL_FROM: "test@test.name"
  MODE_CACHING: true
  MODE_DEBUG: true
  MODE_PROFILING: false
  SECRET_KEY: "1"
  SITE_ID: 1
  TIME_ZONE: "UTC"


travis:
  EMAIL_FROM: "test@test.name"
  MODE_CACHING: true
  MODE_DEBUG: true
  MODE_PROFILING: false
  SECRET_KEY: "1"
  SITE_ID: 1
  TIME_ZONE: "UTC"
