default:
  ALLOWED_HOSTS: []
  DATABASE_URL: ""
  MODE_CACHING: false
  MODE_DEBUG: true
  MODE_PROFILING: false
  SECRET_KEY: ""
  SENTRY_DSN: ""

development:
  MODE_CACHING: false
  MODE_DEBUG: true
  MODE_PROFILING: false

heroku:
  ALLOWED_HOSTS:
    - .sidorov-dev.herokuapp.com
    - .sidorov.dev
    - 127.0.0.1
    - localhost
  MODE_CACHING: true
  MODE_DEBUG: false
  MODE_PROFILING: false

travis:
  DATABASE_URL: "postgresql://postgres@localhost:5432/sd"
  MODE_CACHING: false
  MODE_DEBUG: true
  MODE_PROFILING: false
  SECRET_KEY: "1"
