default:
  ALLOWED_HOSTS: []
  DATABASE_URL: ""
  DEBUG: true
  SECRET_KEY: ""

development:
  DEBUG: true

heroku:
  ALLOWED_HOSTS:
    - 127.0.0.1
    - localhost
    - sidorov-dev.herokuapp.com
    - sidorov.dev
  DEBUG: false

travis:
  DATABASE_URL: "postgresql://postgres@localhost:5432/sd"
  DEBUG: true
  SECRET_KEY: "1"
