# Generated by Django 3.0.6 on 2020-05-31 00:59

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0002_auto_20200413_0015"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.PositiveSmallIntegerField()),
                ("slot0", models.PositiveSmallIntegerField()),
                ("slot1", models.PositiveSmallIntegerField()),
            ],
            options={"ordering": ("day", "slot0", "slot1"),},
        ),
        migrations.AlterModelOptions(name="calendar", options={"ordering": ("name",)},),
        migrations.RemoveField(model_name="calendar", name="synced",),
        migrations.AlterField(
            model_name="calendar",
            name="ical",
            field=models.TextField(
                blank=True, editable=False, null=True, verbose_name="iCal"
            ),
        ),
        migrations.AlterField(
            model_name="calendar",
            name="synced_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
