# Generated by Django 3.0.6 on 2020-05-24 19:41

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0002_auto_20200413_0015"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.TextField(blank=True, editable=False, null=True)),
                ("start", models.DateTimeField(editable=False)),
                ("end", models.DateTimeField(editable=False)),
                ("summary", models.TextField(editable=False)),
                ("calendar", models.TextField(editable=False)),
            ],
        ),
        migrations.RemoveField(model_name="calendar", name="synced",),
        migrations.AlterField(
            model_name="calendar",
            name="ical",
            field=models.TextField(
                blank=True, editable=False, null=True, verbose_name="iCal"
            ),
        ),
        migrations.AlterField(
            model_name="calendar",
            name="synced_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
