# Generated by Django 4.1.1 on 2022-10-02 16:57

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0003_auto_20200531_0359"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendar",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="slot",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
