# Generated by Django 3.0.6 on 2020-05-30 23:12

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0003_auto_20200524_2241"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.PositiveSmallIntegerField()),
                ("slot0", models.PositiveSmallIntegerField()),
                ("slot1", models.PositiveSmallIntegerField()),
            ],
            options={"ordering": ("day", "slot0", "slot1"),},
        ),
        migrations.DeleteModel(name="Event",),
        migrations.AlterModelOptions(name="calendar", options={"ordering": ("name",)},),
    ]
