name: Deploy to GitHub Pages

on:
  page_build:
  push:
    branches:
      - master
  workflow_dispatch:


defaults:
  run:
    working-directory: ./services/frontend/


jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: ./services/frontend/
          cache: npm
          node-version: '21.6.2'

      - name: Install dependencies
        run: npm install
        working-directory: ./services/frontend/

      - name: build
        run: |
          npm run build
        working-directory: ./services/frontend/

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          # this should match the `pages` option in your adapter-static options
          path: './services/frontend/build/'

  deploy-site:
    needs: build-site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
